//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Bet')
export class BetEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  betType: string;

  @Column('real', { nullable: true })
  betAmount: number;

  @Column('integer', { nullable: true })
  bankAccountNumber: number;

  @Column('integer', { nullable: true })
  ifcCode: number;

  @Column('integer', { nullable: true })
  bankName: number;

  @Column('integer', { nullable: true })
  walletFacility: number;
}
