//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Transaction')
export class TransactionEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  transactionMethod: string;

  @Column('real', { nullable: true })
  transactionAmount: number;

  @Column('date', { nullable: true })
  transactionDate: Date;

  @Column('integer', { nullable: true })
  userId: number;

  @Column('text', { nullable: true })
  transactionStatus: string;
}
