//Source code generated by AppGPT (www.appgpt.tech)
import {
  Datagrid,
  List,
  EditButton,
  Edit,
  SimpleForm,
  Create,
  SelectColumnsButton,
  DatagridConfigurable,
  TopToolbar,
  CreateButton,
  ExportButton,
  FilterButton,
  //Field controls
  BooleanField,
  DateField,
  EmailField,
  ImageField,
  NumberField,
  ReferenceField,
  TextField,
  UrlField,
  //Input controls
  BooleanInput,
  DateInput,
  EmailInput,
  ImageInput,
  NumberInput,
  ReferenceInput,
  TextInput,
  UrlInput,
  PasswordInput,
} from 'react-admin';
import { useRecordContext } from 'react-admin';
import { Grid } from '@mui/material';
const ReadOnlyPasswordField = ({ record, source }) => {
  // You can customize the way you display the password here, e.g., mask it with asterisks
  const maskedPassword = '********';

  return <span>{maskedPassword}</span>;
};
const ListActions = () => (
  <TopToolbar>
    <FilterButton />
    <CreateButton />
    <ExportButton />
    <SelectColumnsButton />
  </TopToolbar>
);
const BetTitle = () => {
  const record = useRecordContext();
  return <span>Bet {record ? `"${record.betType}"` : ''}</span>;
};

export const BetList = () => (
  <List actions={<ListActions />} filters={ResourceFilters}>
    <DatagridConfigurable>
      <TextField source="betType" />
      <NumberField source="betAmount" />
      <ReferenceField source="bankAccountNumber" reference="User" />
      <ReferenceField source="ifcCode" reference="User" />
      <ReferenceField source="bankName" reference="User" />
      <ReferenceField source="walletFacility" reference="Wallet" />
      <EditButton />
    </DatagridConfigurable>
  </List>
);

export const BetEdit = () => (
  <Edit title={<BetTitle />}>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <TextInput source="betType" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="betAmount" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="bankAccountNumber" reference="User" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="ifcCode" reference="User" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="bankName" reference="User" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="walletFacility" reference="Wallet" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Edit>
);

export const BetCreate = () => (
  <Create>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <TextInput source="betType" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="betAmount" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="bankAccountNumber" reference="User" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="ifcCode" reference="User" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="bankName" reference="User" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="walletFacility" reference="Wallet" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Create>
);

const ResourceFilters = [
  <TextInput source="q" label="Search" alwaysOn />,
  ,
  ,
  <ReferenceInput
    source="bankAccountNumber"
    label="bankAccountNumber"
    reference="User"
    alwaysOn
  />,
  <ReferenceInput source="ifcCode" label="ifcCode" reference="User" alwaysOn />,
  <ReferenceInput
    source="bankName"
    label="bankName"
    reference="User"
    alwaysOn
  />,
  <ReferenceInput
    source="walletFacility"
    label="walletFacility"
    reference="Wallet"
    alwaysOn
  />,
];
