//Source code generated by AppGPT (www.appgpt.tech)
import { Admin, Resource, CustomRoutes } from 'react-admin';
import { customDataProvider } from './dataProvider';
import fakeDataProvider from 'ra-data-fakerest';
import { Dashboard } from './dashboard';
import { authProvider, apInitialize } from './authProvider';
import { i18nProvider } from './i18nProvider';
import LoginPage, { Login } from './Login';
import data from './data';
import { UserList, UserCreate, UserEdit } from './resources/User';
import { BetList, BetCreate, BetEdit } from './resources/Bet';
import {
  TransactionList,
  TransactionCreate,
  TransactionEdit,
} from './resources/Transaction';
import { WalletList, WalletCreate, WalletEdit } from './resources/Wallet';
import UserIcon from '@mui/icons-material/AccountCircle';
import BetIcon from '@mui/icons-material/Casino';
import TransactionIcon from '@mui/icons-material/Payment';
import WalletIcon from '@mui/icons-material/AccountBalance';
// SUPERTOKENS
import React from 'react';
import SuperTokens, {
  SuperTokensWrapper,
  getSuperTokensRoutesForReactRouterDom,
} from 'supertokens-auth-react';
import ThirdPartyPasswordless from 'supertokens-auth-react/recipe/thirdpartypasswordless';
import Session from 'supertokens-auth-react/recipe/session';
import { BrowserRouter, Routes, Route, Link } from 'react-router-dom';
import * as reactRouterDom from 'react-router-dom';
let sessionFn = Session.init();
SuperTokens.init({
  appInfo: {
    appName: import.meta.env.VITE_SUPERTOKENS_APPNAME,
    apiDomain: import.meta.env.VITE_BACKEND_DOMAIN,
    websiteDomain: import.meta.env.VITE_SUPERTOKENS_WEBSITEDOMAIN,
    apiBasePath: import.meta.env.VITE_BACKEND_APIPATH + '/auth',
    websiteBasePath: import.meta.env.VITE_SUPERTOKENS_WEBSITEBASEPATH,
  },
  recipeList: [
    ThirdPartyPasswordless.init({
      contactMethod: 'EMAIL',
      signInUpFeature: {
        providers: [
          ThirdPartyPasswordless.Github.init(),
          //ThirdPartyPasswordless.Google.init(),
          //ThirdPartyPasswordless.Facebook.init(),
          //ThirdPartyPasswordless.Apple.init(),
        ],
      },
    }),
    sessionFn,
  ],
});
apInitialize(Session);
// END SUPERTOKENS
let dataProvider: any;
if (import.meta.env.VITE_USE_BACKEND_DATA === 'true') {
  dataProvider = customDataProvider(
    import.meta.env.VITE_BACKEND_DOMAIN +
      import.meta.env.VITE_BACKEND_APIPATH +
      '/proxy',
  );
} else {
  dataProvider = fakeDataProvider(data.defaultData);
}

const App = () => (
  <SuperTokensWrapper>
    <BrowserRouter basename="/abf170c8a">
      <Admin
        authProvider={
          import.meta.env.VITE_ENVIRONMENT != 'DEV' ? authProvider : undefined
        }
        requireAuth
        loginPage={LoginPage}
        dataProvider={dataProvider}
        i18nProvider={i18nProvider}
        dashboard={Dashboard}
      >
        <Resource
          name="User"
          options={{ label: 'User' }}
          list={UserList}
          create={UserCreate}
          edit={UserEdit}
          recordRepresentation="phoneNumber"
          icon={UserIcon}
        />
        <Resource
          name="Bet"
          options={{ label: 'Bet' }}
          list={BetList}
          create={BetCreate}
          edit={BetEdit}
          recordRepresentation="betType"
          icon={BetIcon}
        />
        <Resource
          name="Transaction"
          options={{ label: 'Transaction' }}
          list={TransactionList}
          create={TransactionCreate}
          edit={TransactionEdit}
          recordRepresentation="transactionMethod"
          icon={TransactionIcon}
        />
        <Resource
          name="Wallet"
          options={{ label: 'Wallet' }}
          list={WalletList}
          create={WalletCreate}
          edit={WalletEdit}
          recordRepresentation="balance"
          icon={WalletIcon}
        />
        <CustomRoutes noLayout>
          {/*This renders the login UI on the /auth route*/}
          {getSuperTokensRoutesForReactRouterDom(reactRouterDom)}
          {/*Your app routes*/}
        </CustomRoutes>
      </Admin>
    </BrowserRouter>
  </SuperTokensWrapper>
);

export default App;
